/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.io.IOException;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author root
 */
public class IssueBookFrame extends javax.swing.JFrame {

    String Date = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));

    /**
     * Creates new form IssueBookFrame
     */
    public IssueBookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(26, 19, 19));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(67, 59, 59));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        jPanel5.setBackground(new java.awt.Color(50, 43, 43));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 110));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));
        jTextField1.setText("0");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 410, 380));

        jPanel3.setBackground(new java.awt.Color(65, 57, 57));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Details");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Member Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));

        jPanel4.setBackground(new java.awt.Color(47, 37, 37));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 370, 110));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 90, -1));
        jTextField2.setText("0");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 420, 380));

        jButton4.setBackground(new java.awt.Color(15, 240, 200));
        jButton4.setText("Issue Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 100, -1));

        jButton5.setBackground(new java.awt.Color(0, 255, 204));
        jButton5.setText("<-Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 504, 120, 20));
        jLabel7.setText(Date);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(912, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
                new HomeFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String s1, s2;
            s2 = "";
            s1 = jTextField1.getText().toString();
            System.out.println("1");
            Database dm = new Database();
            if (!s1.equals(s2)) {
                System.out.println("2");
                try {
                    System.out.println("3");
                    int i = Integer.parseInt(s1);
                    String search = "select Name from book where Book_id='" + i + "'";
                    ResultSet rs = dm.executeQuery(search);
                    
                    //  System.out.println("username:" + rs.getString(1) + "  password " + rs.getString(2));
                    System.out.println("4");
                    if (rs.next()) {
                        System.out.println("5");
                        jTextField3.setText(rs.getString(1));
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Book ID");
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }
            } else {
                JOptionPane.showMessageDialog(null, "put something");
                
            }   dm.connClose();
        } catch (IOException ex) {
            Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            
            Database dm = new Database();
            String s1, s2;
            s2 = "";
            s1 = jTextField2.getText();
            if (s1.equals(s2)) {
                JOptionPane.showMessageDialog(null, "put something");
                
            } else {
                
                try {
                    int i = Integer.parseInt(jTextField2.getText());
                    String search = "select * from member where Member_id='" + i + "'";
                    ResultSet rs = dm.executeQuery(search);
                    
                    //  System.out.println("username:" + rs.getString(1) + "  password " + rs.getString(2));
                    if (rs.next()) {
                        jTextField4.setText(rs.getString(2));
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "User Not Exists ");
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }

            }
        } catch (IOException ex) {
            Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String membername, department, member_type;
            int bookid, memberid;
            String Checkbookid, Checkmemberid;
            Checkbookid = jTextField1.getText().toString();
            Checkmemberid = jTextField2.getText().toString();
            //Integer.parseInt(jTextField2.getText().toString()); jTextField4.getText().toString();
            //department = t14.getText();
            // member_type = t17.getText();
            String empty = "";
            int i, j;
            i = j = 0;
            // s3 = t1.getText();
            // s4 = t11.getText();
            //JOptionPane.showMessageDialog(null, "s3 :" + s3 + "\ns4   :" + s4);
            Database db = new Database();
            if (Checkmemberid.equals(empty) || Checkmemberid.equals(empty)) {
                JOptionPane.showMessageDialog(null, "Blank Character is not allowed");
            } else {
                memberid = Integer.parseInt(jTextField2.getText().toString());
                bookid = Integer.parseInt(jTextField1.getText().toString());
                if (bookid == i || memberid == j) {
                    JOptionPane.showMessageDialog(null, "First input something");
                    
                } else {
                    System.out.println("error: 0? ");
                    String insert, check, check1, check2, check3, check4, check5;
                    check1 = "select count(*) from issue Where Member_id='" + memberid + "'";
                    check2 = "select Member_id,Book_id from issue Where Member_id='" + memberid + "' AND Book_id='" + bookid + "'";
                    check3 = "select * from issue Where Book_id='" + bookid + "'";
                    check4 = "select * from book Where Book_id='" + bookid + "'";
                    check5 = "select * from member Where Member_id='" + memberid + "'";
                    try {
                        System.out.println("error: 1? ");
                        ResultSet rs1 = db.executeQuery(check1);
                        // if( !rs1.isBeforeFirst()){ System.out.println("no data");}
                        
                        rs1.next();
                        int num = rs1.getInt(1);
                        
                        System.out.println("num=" + num);
                        if (num >= 2) {
                            //rs1.close();
                            JOptionPane.showMessageDialog(null, "HE cant took book more beacuse limit is : " + num);
                        } else {
                            System.out.println("else 1");
                            ResultSet rs2 = db.executeQuery(check2);
                            if (rs2.next()) {
                                JOptionPane.showMessageDialog(null, "The user that request for the book,he already have");
                                
                            } else {
                                System.out.println("else 2");
                                ResultSet rs3 = db.executeQuery(check3);
                                if (rs3.next()) {
                                    JOptionPane.showMessageDialog(null, "Book can't be distrubuted of same id");
                                    
                                } else {
                                    System.out.println("else 3");
                                    Database checkdb = new Database();
                                    ResultSet crs1 = checkdb.executeQuery(check4);
                                    //  ResultSet crs2=checkdb.executeQuery(check5);
                                    System.out.println("else 4");
                                    if (crs1.next()) {
                                        System.out.println("else 5");
                                        ResultSet rs4 = db.executeQuery(check4);
                                        rs4.next();
                                        int bkid = Integer.parseInt(rs4.getString(1));
                                        String bkname = rs4.getString(2);
                                        
                                        if (!rs4.isBeforeFirst()) {
                                            System.out.println("rs4 no data");
                                        }
                                        System.err.println("date : "+Date);
                                        //
                                        
                                        //  if( !rs5.isBeforeFirst()){ System.out.println("rs5 no data");}
                                        // if (rs4.next() ) {
                                        // if(rs5.next()){
                                        //  rs5.next();
                                        ResultSet rs5 = db.executeQuery(check5);
                                        rs5.next();
                                        System.out.println("inside if");
                                        int memid = Integer.parseInt(rs5.getString(1));
                                        String memname = rs5.getString(2);
                                        String memtype = rs5.getString(7);
                                        // int bkid = Integer.parseInt(rs4.getString(1));
                                        //  String bkname = rs4.getString(2);
                                        System.out.println("values : " + memtype + memberid + memname + bkname + bkid);
                                        insert = "INSERT INTO issue (Member_id,Book_id,Member_Name,Book_Name,Member_Type,Issue_Date) VALUES('" + memid + "','" + bkid + "','" + memname + "','" + bkname + "','" + memtype + "', STR_TO_DATE('" + Date + "','%d-%m-%Y') )";
                                        db.executeUpdate(insert);
                                        JOptionPane.showMessageDialog(null, "Issued \n Bookid: " + bookid + " \n To Memberid : " + memberid);
                                        db.connClose();
                                        //  }
                                    } else {
                                        
                                        JOptionPane.showMessageDialog(null, "Invalid BookID or Member ID");
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                }
            }
        } catch (IOException ex) {
            Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
