/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.io.IOException;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class ReturnBookFrame extends javax.swing.JFrame {

    String Date = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));

    /**
     * Creates new form ReturnBookFrame
     */
    public ReturnBookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(30, 24, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 102));
        jButton2.setText("<-Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(45, 42, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, -1));

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Member ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 380, 370));

        jPanel3.setBackground(new java.awt.Color(52, 48, 48));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 400, 370));

        jButton3.setText("Return Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 513, 120, 30));

        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 514, 100, 20));
        jLabel5.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
                new HomeFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            
            Database dm = new Database();
            String s1, s2;
            s2 = "";
            s1 = jTextField1.getText();
            if (s1.equals(s2)) {
                JOptionPane.showMessageDialog(null, "put something");
                
            } else {
                
                try {
                    int i = Integer.parseInt(jTextField1.getText());
                    String search = "select * from issue Where Member_id='" + i + "'";
                    ResultSet rs = dm.executeQuery(search);
                    
                    //  System.out.println("username:" + rs.getString(1) + "  password " + rs.getString(2));
                    if (rs.next()) {
                        jTextField3.setText(rs.getString(3));
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "User Not Exists ");
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }
                
            }   dm.connClose();
        } catch (IOException ex) {
            Logger.getLogger(ReturnBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String s1, s2;
            s2 = "";
            s1 = jTextField2.getText().toString();
            int memberid = Integer.parseInt(jTextField1.getText().toString());
            System.out.println("1");
            Database dm = new Database();
            if (!s1.equals(s2)) {
                System.out.println("2");
                try {
                    System.out.println("3");
                    int i = Integer.parseInt(s1);
                    String search = "select * from issue Where Book_id='" + i + "' AND Member_id='" + memberid + "'";
                    ResultSet rs = dm.executeQuery(search);
                    
                    //  System.out.println("username:" + rs.getString(1) + "  password " + rs.getString(2));
                    System.out.println("4");
                    if (rs.next()) {
                        System.out.println("5");
                        jTextField4.setText(rs.getString(4));
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Book ID");
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }
            } else {
                JOptionPane.showMessageDialog(null, "put something");
                
            }   dm.connClose();
        } catch (IOException ex) {
            Logger.getLogger(ReturnBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String empty = "";
            
            Database db = new Database();
            String s1 = jTextField1.getText().toString();
            String s2 = jTextField2.getText().toString();
            
            if (s1.equals(empty) || s2.equals(empty)) {
                JOptionPane.showMessageDialog(null, "What You Want To Return?");
            } else {
                
                try {
                    int member_id, book_id;
                    String member_name, book_name, member_type, issue_date, return_date;
                    //= Integer.parseInt(t11.getText());
                    member_id = Integer.parseInt(s1);
                    book_id = Integer.parseInt(s2);
                    
                    //String check1,check2;
                    //    String book="select * from Book where  "
                    // String check1 = "select member_id,book_id,issue_date,return_date from ReturnTable Where member_id='" + member_id + "' AND book_id='" + book_id + "' AND issue_date='" + issue_date + "' AND return_date='" + return_date + "'";
                    String issue_table = "select * from issue Where Member_id='" + member_id + "' AND Book_id='" + book_id + "'";
                    
                    ResultSet rs1 = db.executeQuery(issue_table);
                    if (rs1.next()) {
                        member_name = rs1.getString(3);
                        book_name = rs1.getString(4);
                        member_type = rs1.getString(5);
                        issue_date = rs1.getString(6);
                        return_date = Date;
                        System.err.println("date is : Issue : "+issue_date+" Return Date : "+return_date);
                        String insert = "INSERT INTO return_table (Member_id,Book_id,Member_Name,Book_Name,Member_Type,Issue_Date,Return_Date) Values('" + member_id + "','" + book_id + "','" + member_name + "','" + book_name + "','" + member_type + "', STR_TO_DATE('" + issue_date + "','%Y-%m-%d'), STR_TO_DATE('" + return_date + "','%d-%m-%Y'))";
                        String delete = "delete from issue where Member_id='" + member_id + "' AND Book_id='" + book_id + "'";
                        
                        db.executeUpdate(insert);
                        db.executeUpdate(delete);
                        JOptionPane.showMessageDialog(null, "Returned ! ");
                        db.connClose();
                    }else{
                        JOptionPane.showMessageDialog(null, "User Not extist || input wrong");
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(ReturnBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
